const USER_NAME_OR_PASSWORD_REQUIRED = "USER_NAME_OR_PASSWORD_REQUIRED";
const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
const UNPROMISSION = "UNPROMISSION"
module.exports = {
  USER_NAME_OR_PASSWORD_REQUIRED,
  USER_ALREADY_EXISTS,
  UNPROMISSION
};
